import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {saveCompanion} from '../extensions/visuals/companions.ts';
import {verifyCompanion} from '../extensions/visuals/verify.ts';
const root=fileURLToPath(new URL('../',import.meta.url));
const assetsDir=path.join(root,'examples/visuals');
const wrap=(topic:string,body:string,style='')=>`<!doctype html><html lang="en"><head><style>${style}</style></head><body><main><header class="pi-header"><div class="pi-brand"><span>π</span> Pi-learn</div><div class="pi-eyebrow">${topic} / Visual companion</div></header>${body}</main></body></html>`;
function quiz(prompt:string,options:{text:string,correct:boolean,explanation:string}[],hint:string,multiple=false){return `<form class="pi-quiz" data-pi-quiz><fieldset><legend>${prompt}</legend>${options.map(o=>`<label class="pi-option"><input type="${multiple?'checkbox':'radio'}" name="practice" data-pi-answer="${o.correct}" data-pi-explanation="${o.explanation}">${o.text}</label>`).join('')}<div class="pi-controls"><button type="submit">Check answer</button><button type="button" class="pi-secondary" data-pi-show-hint>Hint</button><button type="button" class="pi-secondary" data-pi-retry>Retry</button></div><p class="pi-feedback" role="status" data-pi-feedback hidden></p><p data-pi-hint hidden>${hint}</p></fieldset></form>`;}
function steps(items:{title:string,text:string}[]){return `<section class="pi-steps" data-pi-steps aria-label="Step-by-step explanation">${items.map((s,i)=>`<article class="pi-step" data-pi-step ${i?'hidden':''}><h2><span class="pi-number">${i+1}</span> ${s.title}</h2><p>${s.text}</p></article>`).join('')}<div class="pi-controls"><button type="button" class="pi-secondary" data-pi-prev>Back</button><button type="button" data-pi-next>Next</button><span role="status" data-pi-step-status></span></div></section>`;}
const fractions=wrap('Mathematics',`<div class="pi-grid pi-hero"><section><h1>See the whole.<br><span class="pi-accent">Understand the parts.</span></h1><p>Three quarters means selecting three of four equal parts. Change the selection and watch the relationship.</p><p class="pi-equation">¾ = 0.75 = 75%</p></section><section data-pi-fraction aria-label="Fraction experiment"><div class="pi-diagram"><svg viewBox="0 0 400 400" role="img" aria-label="Circle divided into four equal quadrants"><title>Four equal quarters</title><path data-pi-part d="M200 200V20A180 180 0 0 1 380 200Z" fill="#1249db"/><path data-pi-part d="M200 200H380A180 180 0 0 1 200 380Z" fill="#1249db"/><path data-pi-part d="M200 200V380A180 180 0 0 1 20 200Z" fill="#1249db"/><path data-pi-part d="M200 200H20A180 180 0 0 1 200 20Z" fill="#faf7ef"/><circle cx="200" cy="200" r="180" fill="none" stroke="#112035" stroke-width="2"/><path d="M200 20V380M20 200H380" stroke="#faf7ef" stroke-width="5"/></svg></div><div class="pi-controls"><label for="selected">Selected parts</label><input id="selected" type="range" min="0" max="4" value="3" step="1"><output class="pi-equation" data-pi-fraction-value aria-live="polite">3/4 = 75%</output></div></section></div><aside class="pi-insight"><h2>Equal parts matter.</h2><p>The denominator counts equal parts in the whole. The numerator counts selected parts. Dividing the numerator by the denominator gives the decimal value.</p></aside>${steps([{title:'Divide',text:'Partition the whole into four equal-sized pieces. Each piece is one quarter.'},{title:'Select',text:'Choose three pieces. Together they make three quarters; one quarter is left.'},{title:'Connect',text:'3 ÷ 4 = 0.75. Multiply by 100 to express the same quantity as 75%.'}])}${quiz('Which fraction equals 75%?', [{text:'4/3',correct:false,explanation:'Four thirds is greater than one whole.'},{text:'3/4',correct:true,explanation:'Three divided by four is 0.75, or 75%.'},{text:'1/4',correct:false,explanation:'One quarter is 25%.'}], 'Divide the top number by the bottom number.')}`);
const nitrogen=wrap('Soil science',`<h1>Follow nitrogen.<br><span class="pi-accent">Name the transformation.</span></h1><p>Nitrogen changes chemical form. Each transformation has different organisms, conditions, and consequences.</p><section class="nitrogen-map" aria-label="Nitrogen transformation map"><article class="nitrogen-node"><span class="pi-number">1</span><h2>Atmospheric N₂</h2><p><strong>Fixation</strong> converts nitrogen gas into ammonia, which forms ammonium in soil.</p><p class="pi-equation">N₂ → NH₃ / NH₄⁺</p></article><article class="nitrogen-node"><span class="pi-number">2</span><h2>Soil ammonium</h2><p><strong>Nitrification</strong> oxidises ammonium via nitrite to nitrate, usually under aerobic conditions.</p><p class="pi-equation">NH₄⁺ → NO₂⁻ → NO₃⁻</p></article><article class="nitrogen-node"><span class="pi-number">3</span><h2>Living tissue</h2><p><strong>Assimilation</strong> incorporates absorbed ammonium or nitrate into organic compounds.</p><p class="pi-equation">NH₄⁺ / NO₃⁻ → organic N</p></article><article class="nitrogen-node"><span class="pi-number">4</span><h2>Organic residues</h2><p><strong>Ammonification</strong> converts organic nitrogen in residues back into ammonium.</p><p class="pi-equation">Organic N → NH₄⁺</p></article></section><aside class="pi-insight"><h2>A branch, not a single loop.</h2><p>Denitrification reduces nitrate to gases such as N₂O and N₂, typically where oxygen is limited. Nitrate can also be lost through leaching. These routes differ from plant uptake.</p></aside>${steps([{title:'Separate the forms',text:'Atmospheric nitrogen gas, ammonium, nitrate, and organic nitrogen are different pools. Plants generally take up ammonium and nitrate; they do not directly assimilate atmospheric N₂.'},{title:'Separate the processes',text:'Fixation begins with N₂. Nitrification begins with NH₄⁺. Ammonification begins with organic nitrogen. Name the process by its starting and ending forms.'},{title:'Connect conditions to losses',text:'Oxygen-limited soil can favour denitrification. Nitrate is also mobile in soil water, so leaching is another loss pathway.'}])}${quiz('Select both transformations that produce ammonium or ammonia.',[{text:'Nitrification',correct:false,explanation:'Nitrification consumes ammonium to produce nitrite and nitrate.'},{text:'Biological nitrogen fixation',correct:true,explanation:'Fixation converts N₂ into ammonia.'},{text:'Ammonification',correct:true,explanation:'Ammonification releases ammonium from organic nitrogen.'}], 'Look for processes ending at NH₃ or NH₄⁺.',true)}`,'.nitrogen-map{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:20px;margin:32px 0}.nitrogen-node{border-top:3px solid var(--pi-orange);padding:22px;background:white}.nitrogen-node h2{font-size:30px}.nitrogen-node .pi-equation{font-size:25px;overflow-wrap:anywhere}');
const plant=fs.readFileSync(path.join(root,'examples/source/plant-deficiencies.html'),'utf8')
  .replace('<!-- plant-illustration -->', fs.readFileSync(path.join(root,'examples/source/plant-nutrient-mobility.svg'),'utf8'));

for (const [filename,title,htmlContent] of [['fractions.html','Understand fractions',fractions],['nitrogen-cycle.html','Nitrogen transformations',nitrogen],['plant-deficiencies.html','Plant deficiency patterns',plant]]) {
  const saved=saveCompanion({assetsDir,filename,title,htmlContent});
  if(process.argv.includes('--verify')) {
    const result=await verifyCompanion(saved.htmlPath,path.join(root,'.visual-previews'));
    console.log(JSON.stringify({filename,...result}));
    if(result.status!=='passed') process.exitCode=1;
  }else console.log(saved.htmlPath);
}
